name: Node.js Docker CI/CD

on:
  workflow_dispatch:

jobs:

  # -------------------------
  # 1. Test Node.js App
  # -------------------------
  test:
    name: Test Application
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: github

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test


  # -------------------------
  # 2. Build & Push Docker
  # -------------------------
  build-and-push:
    name: Build and Push Docker Image
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/nodejs-devops-app:latest \
            ./github

      - name: Push Docker image
        run: |
          docker push \
            ${{ secrets.DOCKER_USERNAME }}/nodejs-devops-app:latest


  # -------------------------
  # 3. Deploy to EC2
  # -------------------------
  deploy:
    name: Deploy to EC2
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/nodejs-devops-app:latest

            docker stop nodejs-app || true
            docker rm nodejs-app || true

            docker run -d \
              --name nodejs-app \
              -p 3000:3000 \
              ${{ secrets.DOCKER_USERNAME }}/nodejs-devops-app:latest

            docker ps